//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prog6_GrandFinale.PokemonService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pokemon", Namespace="http://schemas.datacontract.org/2004/07/Prog6_GrandFinale.WCF")]
    [System.SerializableAttribute()]
    public partial class Pokemon : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateOfBirthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LevelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateOfBirth {
            get {
                return this.DateOfBirthField;
            }
            set {
                if ((this.DateOfBirthField.Equals(value) != true)) {
                    this.DateOfBirthField = value;
                    this.RaisePropertyChanged("DateOfBirth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Level {
            get {
                return this.LevelField;
            }
            set {
                if ((this.LevelField.Equals(value) != true)) {
                    this.LevelField = value;
                    this.RaisePropertyChanged("Level");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PokemonService.IPokemonService")]
    public interface IPokemonService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokemonService/GetPokemons", ReplyAction="http://tempuri.org/IPokemonService/GetPokemonsResponse")]
        Prog6_GrandFinale.PokemonService.Pokemon[] GetPokemons();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokemonService/GetPokemons", ReplyAction="http://tempuri.org/IPokemonService/GetPokemonsResponse")]
        System.Threading.Tasks.Task<Prog6_GrandFinale.PokemonService.Pokemon[]> GetPokemonsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokemonService/CreatePokemons", ReplyAction="http://tempuri.org/IPokemonService/CreatePokemonsResponse")]
        Prog6_GrandFinale.PokemonService.Pokemon CreatePokemons(Prog6_GrandFinale.PokemonService.Pokemon composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPokemonService/CreatePokemons", ReplyAction="http://tempuri.org/IPokemonService/CreatePokemonsResponse")]
        System.Threading.Tasks.Task<Prog6_GrandFinale.PokemonService.Pokemon> CreatePokemonsAsync(Prog6_GrandFinale.PokemonService.Pokemon composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPokemonServiceChannel : Prog6_GrandFinale.PokemonService.IPokemonService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PokemonServiceClient : System.ServiceModel.ClientBase<Prog6_GrandFinale.PokemonService.IPokemonService>, Prog6_GrandFinale.PokemonService.IPokemonService {
        
        public PokemonServiceClient() {
        }
        
        public PokemonServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PokemonServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokemonServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PokemonServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Prog6_GrandFinale.PokemonService.Pokemon[] GetPokemons() {
            return base.Channel.GetPokemons();
        }
        
        public System.Threading.Tasks.Task<Prog6_GrandFinale.PokemonService.Pokemon[]> GetPokemonsAsync() {
            return base.Channel.GetPokemonsAsync();
        }
        
        public Prog6_GrandFinale.PokemonService.Pokemon CreatePokemons(Prog6_GrandFinale.PokemonService.Pokemon composite) {
            return base.Channel.CreatePokemons(composite);
        }
        
        public System.Threading.Tasks.Task<Prog6_GrandFinale.PokemonService.Pokemon> CreatePokemonsAsync(Prog6_GrandFinale.PokemonService.Pokemon composite) {
            return base.Channel.CreatePokemonsAsync(composite);
        }
    }
}
